### PR TITLE
Update KOPS to 1.17.0

### PR DESCRIPTION
**Pull request by rspechenkin**
Purpose of this PR:

Updates KOPS to 1.17.0 to avoid this error:

`error reading cluster configuration: error reading cluster configuration "kube3.evetech.net": error parsing s3://evetech-kops-configs/kube3.evetech.net/config: no kind "Cluster" is registered for version "kops.k8s.io/v1alpha2`

### CODE REVIEW

**Comment by peturgq** [comment]
❯ wget https://github.com/kubernetes/kops/releases/download/v.17.0/kops-linux-amd64
--2020-11-27 12:40:33--  https://github.com/kubernetes/kops/releases/download/v.17.0/kops-linux-amd64
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving github.com (github.com)... 140.82.121.4
Connecting to github.com (github.com)|140.82.121.4|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-11-27 12:40:39 ERROR 404: Not Found.

This release doesn't seem to exist, I'd look and confirm that the release exists in https://github.com/kubernetes/kops/releases/

**Comment by rspechenkin** [comment]
> ❯ wget https://github.com/kubernetes/kops/releases/download/v.17.0/kops-linux-amd64
> --2020-11-27 12:40:33-- https://github.com/kubernetes/kops/releases/download/v.17.0/kops-linux-amd64
> Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
> Resolving github.com (github.com)... 140.82.121.4
> Connecting to github.com (github.com)|140.82.121.4|:443... connected.
> HTTP request sent, awaiting response... 404 Not Found
> 2020-11-27 12:40:39 ERROR 404: Not Found.
> 
> This release doesn't seem to exist, I'd look and confirm that the release exists in https://github.com/kubernetes/kops/releases/

The version in your request is not the same as the version in the PR. In your request it's v.17.0 and in the PR it's v1.17.0

**Comment by peturgq** [comment]
> > ❯ wget https://github.com/kubernetes/kops/releases/download/v.17.0/kops-linux-amd64
> > --2020-11-27 12:40:33-- https://github.com/kubernetes/kops/releases/download/v.17.0/kops-linux-amd64
> > Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
> > Resolving github.com (github.com)... 140.82.121.4
> > Connecting to github.com (github.com)|140.82.121.4|:443... connected.
> > HTTP request sent, awaiting response... 404 Not Found
> > 2020-11-27 12:40:39 ERROR 404: Not Found.
> > This release doesn't seem to exist, I'd look and confirm that the release exists in https://github.com/kubernetes/kops/releases/
> 
> The version in your request is not the same as the version in the PR. In your request it's v.17.0 and in the PR it's v1.17.0

My bad, I forgot the `1`, This looks good to me then.

**Review by peturgq — APPROVED** [review]

**Comment by rspechenkin** [comment]
> > > ❯ wget https://github.com/kubernetes/kops/releases/download/v.17.0/kops-linux-amd64
> > > --2020-11-27 12:40:33-- https://github.com/kubernetes/kops/releases/download/v.17.0/kops-linux-amd64
> > > Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
> > > Resolving github.com (github.com)... 140.82.121.4
> > > Connecting to github.com (github.com)|140.82.121.4|:443... connected.
> > > HTTP request sent, awaiting response... 404 Not Found
> > > 2020-11-27 12:40:39 ERROR 404: Not Found.
> > > This release doesn't seem to exist, I'd look and confirm that the release exists in https://github.com/kubernetes/kops/releases/
> > 
> > 
> > The version in your request is not the same as the version in the PR. In your request it's v.17.0 and in the PR it's v1.17.0
> 
> My bad, I forgot the `1`, This looks good to me then.

Could you merge it then? I don't have permissions but Nick told me that he gave INFRA folks permissions

**Pull request merged**
